name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "5 3 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |
          This issue is stale because it has been open for 30 days without activity.
          This will be closed in 7 days, unless you add the 'lifecycle/keep-alive' label or comment.
        stale-pr-message: |
          This pull request is stale because it has been open for 30 days without activity.
          This will be closed in 7 days, unless you add the 'lifecycle/keep-alive' label or comment.
        stale-pr-label: 'lifecycle/stale'
        stale-issue-label: 'lifecycle/stale'
        exempt-issue-labels: 'lifecycle/keep-alive'
        exempt-pr-labels: 'lifecycle/keep-alive'
        days-before-stale: 30
        days-before-close: 7
